name: code-style
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  style:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install psychopy dependencies
        run: |
          sudo apt install libusb-1.0-0-dev portaudio19-dev libasound2-dev libsdl2-2.0-0
          curl https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.1-cp39-cp39-linux_x86_64.whl -o wxPython-4.2.1-cp39-cp39-linux_x86_64.whl
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install wxPython-4.2.1-cp39-cp39-linux_x86_64.whl
      - name: Install dependencies
        run: python -m pip install --progress-bar off .[style]
      - name: Run Ruff
        run: ruff check .
      - name: Run isort
        uses: isort/isort-action@master
      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
      - name: Run codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          skip: './.git,./build,./.mypy_cache,./.pytest_cache'
          ignore_words_file: ./.codespellignore
      - name: Run pydocstyle
        run: pydocstyle .
