name: pytest
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches: [main]
    paths:
      - '**.py'
  workflow_dispatch:
  schedule:
  - cron: '0 8 * * 1'

jobs:
  pytest:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: [3.9, "3.10", "3.11"]
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Update pip and setuptools
        run: python -m pip install --progress-bar off --upgrade pip setuptools wheel
      - name: Install psychopy dependencies
        if: ${{ matrix.os == 'ubuntu' && matrix.python-version == 3.9 }}
        run: |
          sudo apt install libusb-1.0-0-dev portaudio19-dev libasound2-dev libsdl2-2.0-0
          curl https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.1-cp39-cp39-linux_x86_64.whl -o wxPython-4.2.1-cp39-cp39-linux_x86_64.whl
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install wxPython-4.2.1-cp39-cp39-linux_x86_64.whl
      - name: Install psychopy dependencies
        if: ${{ matrix.os == 'ubuntu' && matrix.python-version == 3.10 }}
        run: |
          sudo apt install libusb-1.0-0-dev portaudio19-dev libasound2-dev libsdl2-2.0-0
          curl https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.1-cp310-cp310-linux_x86_64.whl -o wxPython-4.2.1-cp310-cp310-linux_x86_64.whl
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install wxPython-4.2.1-cp39-cp39-linux_x86_64.whl
      - name: Install psychopy dependencies
        if: ${{ matrix.os == 'ubuntu' && matrix.python-version == 3.11 }}
        run: |
          sudo apt install libusb-1.0-0-dev portaudio19-dev libasound2-dev libsdl2-2.0-0
          curl https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.1-cp311-cp311-linux_x86_64.whl -o wxPython-4.2.1-cp311-cp311-linux_x86_64.whl
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install wxPython-4.2.1-cp39-cp39-linux_x86_64.whl
      - name: Install package
        run: python -m pip install --progress-bar off .[test]
      - name: Display system information
        run: mrisim-sys_info --developer
      - name: Run pytest
        run: pytest mrisim --cov=mrisim --cov-report=xml --cov-config=pyproject.toml
      - name: Upload to codecov
        if: ${{ matrix.os == 'ubuntu' && matrix.python-version == 3.9 }}
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
